apiVersion: batch/v1
kind: Job
metadata:
  name: generate-data-job
spec:
  template:
    spec:
      containers:
      - name: data-generator
        image: python:3.12
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        command: ["sh", "-c"]
        args:
          - |
            pip install psycopg2 faker &&
            python3 <<EOF
            import psycopg2
            from faker import Faker
            import random
            import os

            # PostgreSQL connection details
            DB_HOST = "postgresql-cluster-postgresql-ha-postgresql-0.postgresql-cluster-postgresql-ha-postgresql-headless.default.svc.cluster.local"
            DB_PORT = "5432"
            DB_NAME = "pesalink_db"
            DB_USER = "postgres"
            DB_PASSWORD = os.getenv("POSTGRES_PASSWORD")

            fake = Faker()
            fake.unique.clear()
            used_phones = set()

            try:
                print("🔄 Connecting to PostgreSQL...")
                conn = psycopg2.connect(host=DB_HOST, port=DB_PORT, database=DB_NAME, user=DB_USER, password=DB_PASSWORD)
                cur = conn.cursor()
                print("✅ Connected to PostgreSQL.")

                cur.execute("SELECT COUNT(*) FROM users;")
                user_count = cur.fetchone()[0]

                if user_count >= 100000:
                    print("⚠️ User limit reached. No new users inserted.")
                else:
                    remaining_users = 100000 - user_count
                    print(f"🔄 Generating {remaining_users} users...")
                    
                    user_batch = []
                    for _ in range(remaining_users):
                        email = fake.unique.email()
                        phone = f"254{random.randint(100000000, 999999999)}"
                        while phone in used_phones:
                            phone = f"254{random.randint(100000000, 999999999)}"
                        used_phones.add(phone)
                        user_batch.append((fake.name(), email, phone))

                    cur.executemany("INSERT INTO users (name, email, phone) VALUES (%s, %s, %s)", user_batch)
                    conn.commit()

                    print(f"✅ Successfully inserted {remaining_users} users!")

            except psycopg2.OperationalError as db_err:
                print(f"❌ Database Connection Error: {db_err}")
            except Exception as e:
                print(f"❌ Unexpected Error: {e}")
            finally:
                if 'cur' in locals():
                    cur.close()
                if 'conn' in locals():
                    conn.close()
                    print("🔌 PostgreSQL connection closed.")
            EOF
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pesalink-db-secret
              key: password
      restartPolicy: Never
